[package]
name = "runcher"
build = "src/build.rs"
version = "0.1.1"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "A generic launcher for Total War games since Empire: Total War."
license = "MIT"
edition = "2021"
repository = "https://github.com/Frodo45127/rpfm"
categories = ["games"]
keywords = ["totalwar", "modding", "launcher"]
readme = "README.md"
rust-version = "1.64"

[dependencies]

# Internal dependencies.
rpfm_lib = { path = "./../rpfm/rpfm_lib", version = "4.0.6", features = ["integration_log", "integration_git"] }
rpfm_extensions = { version = "4.0.6" }
rpfm_ui_common = { git = "https://github.com/Frodo45127/rpfm.git", branch = "develop" }

# Serialization support.
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

# Config dependencies.
directories = "^4.0"
lazy_static = "^1.4"

# Error managing.
anyhow = "^1.0"
thiserror = "^1.0"

# Basic get/set support.
getset = "^0.1"

# Qt dependencies.
cpp_core = "^0.6"
qt_core = "^0.5"
qt_gui = "^0.5"
qt_widgets = "^0.5"
qt_ui_tools = "^0.5"

# Support for Regex operations.
regex = "^1"

# Support for open files in a native way.
open = "^4"

# Steam Workshop support.
#steam-workshop-api = "^0.2"
steam-workshop-api = { git = "https://github.com/Frodo45127/rs-steam-workshop-api.git" }

# Better iterator support.
itertools = "^0.10"

# Autoupdate support.
self_update = { version = "^0.36", features = ["archive-zip", "compression-zip-deflate", "compression-zip-bzip2", "compression-flate2"] }
tempfile = "^3.1"
zip-extract = "^0.1"
reqwest = "^0.11"

# Windows resources support.
[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[profile.dev]
incremental = true
opt-level = 3         #For performance debugging, check this. Makes compile times longer, but it gives way more accurate-with-release speeds.
