[package]
name = "runcher"
build = "src/build.rs"
version = "0.1.0"
authors = ["Frodo45127 <frodo_gv@hotmail.com>"]
description = "A generic launcher for Total War games since Empire: Total War."
license = "MIT"
edition = "2021"
repository = "https://github.com/Frodo45127/rpfm"
categories = ["games"]
keywords = ["totalwar", "modding", "launcher"]
readme = "README.md"
rust-version = "1.64"

[dependencies]

# Internal dependencies.
rpfm_lib = { path = "../rpfm/rpfm_lib", version = "4.0.4", features = ["integration_log", "integration_git"] }
rpfm_extensions = { path = "../rpfm/rpfm_extensions", version = "4.0.4" }
rpfm_ui_common = { path = "../rpfm/rpfm_ui_common" }

# Serialization support.
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

# Config dependencies.
directories = "^4.0"
lazy_static = "^1.2"

# Error managing.
anyhow = "1.0"
thiserror = "1.0"

# Basic get/set support.
getset = "^0.1"

# Qt dependencies.
cpp_core = "^0.6"
qt_core = "^0.5"
qt_gui = "^0.5"
qt_widgets = "^0.5"
qt_ui_tools = "^0.5"

# Support for Regex operations.
regex = "^1"

# Steam Workshop support.
#steam-workshop-api = "^0.2"
steam-workshop-api = { path = "../rs-steam-workshop-api", version = "0.2" }

# Windows resources support.
[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[profile.dev]
incremental = true
opt-level = 3         #For performance debugging, check this. Makes compile times longer, but it gives way more accurate-with-release speeds.
